### ISSUE TITLE
How can I realize longest prefix match ?

### ISSUE THREAD

**Issue by wujunjenny** [antirez/rax#10]

**Comment by wujunjenny** [comment]
"foo" 1
"foobar" 2
I want to use "foobar123" matched "foobar" 2

**Comment by antirez** [comment]
I think you should seek for `<=` your string, if it's the exact match you found it, otherwise you identify the common prefix with the current key, and seek again `<=` using this sub-key. And so forth. We don't have an explicit API to do so, you have to write your own function basically.
