### ISSUE TITLE
Proper use of `raxFree`? 

### ISSUE THREAD

**Issue by rmosolgo** [antirez/rax#5]
Hi, thanks again for the cool library! I'm not much of a C programmer but since you included such good documentation, novices like me might want to give `rax` a try 😆 

I'm trying to properly free a `rax *`, but this small program fails for me: 

```c 
#include "rax/rax.c"
#include <stdio.h>

int main(void) {
  printf("Start.\n");
  rax *rt = raxNew();
  printf("-> a\n");
  raxInsert(rt, (unsigned char *)"a", 1, (void *)(100), 0);
  printf("-> ab\n");
  raxInsert(rt, (unsigned char *)"ab", 2, (void *)(101), 0);
  printf("-> abc\n");
  raxInsert(rt, (unsigned char *)"abc", 3, (void *)(NULL), 0);
  printf("-> abcd\n");
  raxInsert(rt, (unsigned char *)"abcd", 4, (void *)(NULL), 0);
  printf("-> abc\n");
  raxInsert(rt, (unsigned char *)"abc", 3, (void *)(102), 0);
  printf("-> free\n");
  raxFree(rt);
  printf("Done.\n");
  return 0;
}
```

The output I get is: 

```
$ gcc -c rux_test.c && gcc rux_test.o -o rux_test && ./rux_test
Start.
-> a
-> ab
-> abc
-> abcd
-> abc
-> free
Segmentation fault: 11
```

I expect `Done.` to be the last line of output, but instead, I get a segfault 😭 

Admittedly, I'm not too familiar with proper C tools, so I may have some other mistake. Does anything jump out as improper here? 

Thanks for taking a look, feel free to close this if it's not rax-related!

**Comment by antirez** [comment]
Hello @rmosolgo, I've the feeling you found a bug since you happened to trigger  a part of Rax which is not well tested (see the TODO list about explicitly testing NULL values more properly). I'm investigating and fixing it right now. Thanks!

**Comment by antirez** [comment]
p.s. right now being after the shower since I just finished my daily run! 🏃

**Comment by rmosolgo** [comment]
No hurry, I'm working on a Ruby binding just for fun. I only noticed this when I tried to replace Ruby's `Qnil` with a proper `NULL` in order to use tree compaction. I have plenty of other things to explore in the meantime :)

**Comment by antirez** [comment]
Fixed :-) Thanks.

**Comment by antirez** [comment]
p.s. now your example is part of the regression test.

**Comment by rmosolgo** [comment]
Works for me, thank you!!
